### PR TITLE
Reflect pktvisor metrics to golang types

### PR DESCRIPTION
**Pull request by leoparente**

### CODE REVIEW

**Comment by weyrick** [comment]
Did you test the UI manually to ensure it's parsing ok?

**Comment by leoparente** [comment]
> Did you test the UI manually to ensure it's parsing ok?

I did not. I will do that

**Comment by weyrick** [comment]
> > Did you test the UI manually to ensure it's parsing ok?
> 
> I did not. I will do that

looks ok?

**Comment by leoparente** [comment]
> > > Did you test the UI manually to ensure it's parsing ok?
> > 
> > 
> > I did not. I will do that
> 
> looks ok?
yes!
image

**Review by weyrick — APPROVED** [review]

**Pull request merged**
