### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by ghost**
added codeql analysis - run daily at 00:05 (5 min past midnight)

### CODE REVIEW

**Comment by ghost** [comment]
add @weyrick as a reviewer.

**Review by etaques — APPROVED** [review]
LGTM
However seems that we have a required test is not passing, I will investigate the issue.

**Comment by ghost** [comment]
please reopen this.  It needs to merge to enable scanning of the CPP code.  
 @weyrick @etaques

**Comment by etaques** [comment]
Hello @mmendelsohn-ns1 we have some problems to merge your PR because it was not passing on required tests, however I added your file (codeql) in another PR (https://github.com/ns1labs/pktvisor/pull/343) and closed this one. You can check that is running on https://github.com/ns1labs/pktvisor/actions/runs/2736490734 19 hours ago.

**Pull request closed without merging**
