### PR TITLE
add top no error qnames on dns handler

### LINKED ISSUE #468: Dns Top NOERROR qnames

### PR DESCRIPTION
**Pull request by leoparente**

### CODE REVIEW

**Comment by leoparente** [comment]
@weyrick @rboucher-ns1 I think that new metric would have a high cardinality... wouldn't that be a problem?

**Comment by rboucher-me** [comment]
> @weyrick @rboucher-ns1 I think that new metric would have a high cardinality... wouldn't that be a problem?

I think the cardinality will be very dependent on the DNS traffic profile: it might be high in certain cases, and modest in others. We'll need to look if this overlaps significantly with the qname2 and qname3  top metrics, and see if we need to keep all three.

**Review by rboucher-me — APPROVED** [review]
Looks good to me.

**Comment by weyrick** [comment]
What about putting this in a metric group and turning off by default? I'm definitely reluctant to add this because of cardinality, overlap, and the fact that it's a "shortcut" table (i.e. something you can get by creating the right policy with a filter ... right?)

**Comment by leoparente** [comment]
> What about putting this in a metric group and turning off by default? I'm definitely reluctant to add this because of cardinality, overlap, and the fact that it's a "shortcut" table (i.e. something you can get by creating the right policy with a filter ... right?)

I'm ok to create a new group. but what would be the name for that group?

**Comment by rboucher-me** [comment]
I think it makes sense to have this disabled by default. We will have to revisit these metrics as part of the DNS Handler v2 work, imo.

**Comment by weyrick** [comment]
Ok new group could be "extra top tables" or something? Or just "beta group"?

**Comment by rboucher-me** [comment]
Good question. Making it part of `TopQnames` wouldn't help much... ;)

Would `TopQnameDetails` make sense? (arguably, `topSizedQnameResp` would probably make sense to be in that group too)

**Comment by leoparente** [comment]
@rboucher-ns1 @weyrick `TopQnameDetails` Then?

**Review by rboucher-me — APPROVED** [review]
Looks good.

**Pull request merged**
