### PR TITLE
run-pktvisor.sh IFS fix for args with spaces

### PR DESCRIPTION
**Pull request by rlahnemann**
When including a bpf filter with spaces in PKTVISORD_ARGS, the container fails to start. For example, `-b port 53 and port 53000` will demonstrate this.

The default internal field separator(IFS) is parsing the whitespace in the filter and passing the results as arguments to pktvisord. 

One solution to address this problem is to change the field separator to a semicolon as shown in this PR.

### CODE REVIEW

**Review by weyrick — CHANGES_REQUESTED** [review]
Thanks for this, I wish I would have realized we needed this for the arguments that require spaces. I hate to break backward compatibility here though. How about we do it differently without breaking existing installations: let's use a new variable that is semi colon delimited, call it `PKTVISOR_ARGS` (without the D). We can change the docs to make that the main variable people should use now, and say that `PKTVISORD_ARGS` is deprecated. But in the script we will still accept it as is (with a warning?). Does that work?

**Comment by weyrick** [comment]
... and then when 3.3.x lands, we will instead recommend that config files be used instead of arguments.

**Comment by rlahnemann** [comment]
How about PKTVISORD_ARGS accepts both? We check for presence of `;`  in the string and change IFS accordingly?

**Comment by weyrick** [comment]
> How about PKTVISORD_ARGS accepts both? We check for presence of `;` in the string and change IFS accordingly?

If that won't results in a false positive then yeah that's a good idea. I guess I can't think of a situation were semi colon should appear otherwise.

**Review by weyrick — APPROVED** [review]
great!

**Pull request merged**
